### ISSUE TITLE
VSCode Pulumi YAML Extension: Config values show squiggles (but work as expected)

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-lsp#107]
### What happened?

When usinig the code shown below, VSCode show squiggles under the references to the config values (e.g. `${length}` and `${prefix}` in the code show squiggles and the "Problems" view shows errors like:
```
Missing variable 'length'
Reference to non-existant variable 'length'. Consider adding a 'length' to the variables section.
```

But running the code works as expected. Changing the config values are reflected in the processing.

### Example

```
name: yaml-issue
description: A minimal Random Pulumi YAML program.
runtime: yaml
config:
  length: 
    type: integer
    default: 8
  prefix:
    type: string
    default: goo
variables:
  mylength: ${length}
resources:
  username:
    type: random:RandomPet
    properties:
      length: ${mylength}
      prefix: ${prefix}
outputs:
  name: ${username.id}

```

### Output of `pulumi about`

CLI          
Version      3.142.0
Go Version   go1.23.3
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  random  unknown
language  yaml    unknown

Host     
OS       darwin
Version  15.1
Arch     x86_64

This project is written in yaml

Backend        
Name           pulumi.com

Dependencies:
NAME    VERSION
random  

### Additional context

NOTE: if one changes the `config` title to the deprecated `configuration` title, there are no squiggles and the code still works as expected.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
