### ISSUE TITLE
LSP doesn't understand the plugins block

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-lsp#108]
### What happened?

I have `plugins` configured in Pulumi.yaml to point to a local provider:

```yaml
plugins:
  providers:
    - name: platform
      path: ../../platform
```

VS Code doesn't understand it though and tries to load it from a normal location:

```
Failed to load package 'platform'
Error: no resource plugin 'pulumi-resource-platform' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource platform`
```

Confusingly, it shows this error on the `name` key: 
<img width="754" alt="Image" src="https://github.com/user-attachments/assets/873f7ac1-cfc7-471b-be6f-17ac6f7bf920" />

### Example

```yaml
name: lambda-yaml
description: A minimal Pulumi YAML program
runtime: yaml
plugins:
  providers:
    - name: platform
      path: ../../platform
resources:
  myapp:
    type: platform:LambdaHttpApp
    properties:
      appFolder: .
      entryPoint: index.handler
outputs:
  endpoint: ${myapp.endpoint}
```

### Output of `pulumi about`

```
pulumi about
CLI          
Version      3.143.0
Go Version   go1.23.4
Go Compiler  gc

Plugins
KIND      NAME      VERSION
resource  platform  0.0.2
language  yaml      unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in yaml

Current Stack: mikhail-pulumi-corp/lambda-yaml/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/mikhail-pulumi-corp
User           mikhail-pulumi-corp
Organizations  mikhail-pulumi-corp, pulumi
Token type     personal

Dependencies:
NAME      VERSION
platform  0.0.2
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
