### ISSUE TITLE
Double `:` inserted during completion

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-lsp#55]
### What happened?

> If I type `aws:s3` then the following sequence `:`, `BACKSPACE` `:` , I should get only one `:` but I get two.

### Steps to reproduce

```yaml
name: provider
runtime: yaml
description: A YAML program which uses a provider
resources:
  test:
    type: aws:s3$
```

Type `:` at the cursor (`$`).

### Expected Behavior

Expect a `:` to appear and the next completion to show up.

### Actual Behavior

Two `:`s appear.

### Output of `pulumi about`

On release 0.1.6-pre

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
