### ISSUE TITLE
Tokens with dashes in name throw errors

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-lsp#74]
### What happened?

I defined a resource from an MLC with token `aws-tailscale:index:Bastion`

### Steps to reproduce

Define some resource like so:

```
name: yaml_aws_tailscalebastion
runtime: yaml
resources:
  vpc:
    type: awsx:ec2:Vpc
    properties:
      cidrBlock: "172.20.0.0/22"
  bastion:
    type: "aws-tailscale:index:Bastion"
    properties:
      vpcId: ${vpc.vpcId}
      subnetIds: ${vpc.privateSubnetIds}
      route: "172.20.0.0/22"
      region: "us-west-2"
      
outputs:
  url: ${vpc.vpcId}
```

### Expected Behavior

No errors

### Actual Behavior

<img width="701" alt="image" src="https://user-images.githubusercontent.com/1622940/196241908-c1f43da8-19cf-4860-8c83-1fcb23c424a1.png">

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
